ARG TARGET=aarch64-pc-windows-gnullvm

# Pin by digest to prevent supply-chain tag-swap attacks.
# Renovate will auto-update this digest when new versions are published.
FROM ghcr.io/rust-cross/cargo-zigbuild:latest@sha256:b8364c2c60cdcc9b95c402d17654bff517410926a35678bd89dd924b8158d6ae AS builder
ARG TARGET

RUN rustup target add "$TARGET"

WORKDIR /src
COPY . .

RUN cargo zigbuild --release --target "$TARGET"

FROM scratch
ARG TARGET
COPY --from=builder /src/target/${TARGET}/release/bx.exe /bx.exe
